### ISSUE TITLE
Release libg2o into Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-gbp/libg2o-release#10]
@croesmann  Would you mind releasing `libg2o` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 7 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by croesmann** [comment]
thanks for the reminder! done, see [PR](https://github.com/ros/rosdistro/pull/24827).
