### ISSUE TITLE
Poor performance because build systems adds -DCMAKE_RELEASE_TYPE=None

### ISSUE THREAD

**Issue by roehling** [ros-gbp/libg2o-release#4]
The debhelper's `dh_auto_configure` adds `-DCMAKE_RELEASE_TYPE=None` automatically, which disables all optimizations and makes the resulting G2O libraries really slow.

One possible fix would be to add `-DCMAKE_RELEASE_TYPE=Release` to the `dh_auto_configure` line in `debian/rules.em` in the `debian/*` branches.

**Comment by vrabaud** [comment]
Fixed with https://github.com/ros-gbp/libg2o-release/commit/fe643e64832e0e16c385ef72fc5498877f98d4b3
Farm shows -O2:
http://build.ros.org/job/Ibin_uT32__libg2o__ubuntu_trusty_i386__binary/2/console
Feel free to backport those 4 lines upstream.
