### ISSUE TITLE
Update the ros-kinetic-libg2o

### ISSUE THREAD

**Issue by xiaomouse2004** [ros-gbp/libg2o-release#6]
Please update the ros-kinetic-libg2o to the newest g2o repo. I think this g2o code which is used to produce g2o lib is about 2 years ago. Until now, there are lots of differernce. Please Update the ros-kinetic-libg2o, thanks very much.

**Comment by croesmann** [comment]
The newest g2o (or at least from March 2018) is released into melodic (resp. I am currently resolving some build errors with ARM processors).

To my mind, with kinetic we need to make sure to keep at least API compatibility.
And as you said, there are lots of changes. Do you need any particular fixes? If we could make sure to not break the API, we could of cause update to some more recent version.
